export const ActionTypes = {
  GET_MOVIES_REQUESTED: "GET_MOVIES_REQUESTED",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIES_FAILED: "GET_MOVIES_FAILED",
  GET_SINGLE_MOVIE_REQUESTED: "GET_SINGLE_MOVIE_REQUESTED",
  GET_SINGLE_MOVIE_SUCCESS: "GET_SINGLE_MOVIE_SUCCESS",
  GET_SINGLE_MOVIE_FAILED: "GET_SINGLE_MOVIE_FAILED",
  GET_FAVOURITE_MOVIE: "GET_FAVOURITE_MOVIE",
  REMOVE_FAVOURITE_MOVIE: "REMOVE_FAVOURITE_MOVIE",
  UPDATE_CURRENT_PAGE: "UPDATE_CURRENT_PAGE",
  UPDATE_CURRENT_SEARCH_QUERY: "UPDATE_CURRENT_SEARCH_QUERY",
};
